// For Answers
export const LOAD_ANSWER = 'LOAD_ANSWER';

// For Request Management
export const ADD_FAILED_REQUEST = 'ADD_FAILED_REQUEST';
export const ADD_PENDING_REQUEST = 'ADD_PENDING_REQUEST';
export const CLEAR_FAILED_REQUEST = 'CLEAR_FAILED_REQUEST';
export const CLEAR_QUEUED_REQUEST = 'CLEAR_QUEUED_REQUEST';
export const FINALIZE_REQUEST = 'FINALIZE_REQUEST';
export const QUEUE_REQUEST = 'QUEUE_REQUEST';
